# starship confg
# Disable the newline at the start of the prompt
add_newline = false

[cmd_duration]
min_time = 30

[package]
disabled = true

[kubernetes]
disabled = false
style = "bold blue"

[time]
disabled = false
